### ISSUE TITLE
SV-230379 - known user accounts

### ISSUE THREAD

**Issue by jrmetzger** [mitre/redhat-enterprise-linux-8-stig-baseline-old#33]
×  SV-230379: RHEL 8 must not have unnecessary accounts. (7 failed)
     ✔  root should be listed in allowed users.
     ✔  bin should be listed in allowed users.
     ✔  daemon should be listed in allowed users.
     ✔  adm should be listed in allowed users.
     ✔  lp should be listed in allowed users.
     ✔  sync should be listed in allowed users.
     ✔  shutdown should be listed in allowed users.
     ✔  halt should be listed in allowed users.
     ✔  mail should be listed in allowed users.
     ✔  operator should be listed in allowed users.
     ×  games should be listed in allowed users.
     expected `games` to be in the list: `["root", "bin", "daemon", "adm", "lp", "sync", "shutdown", "halt", "mail", "operator", "nobody", "systemd-bus-proxy", "dbus", "polkitd", "postfix", "sssd", "chrony", "systemd-network", "sshd", "ntp", "vagrant"]`
     ×  ftp should be listed in allowed users.
     expected `ftp` to be in the list: `["root", "bin", "daemon", "adm", "lp", "sync", "shutdown", "halt", "mail", "operator", "nobody", "systemd-bus-proxy", "dbus", "polkitd", "postfix", "sssd", "chrony", "systemd-network", "sshd", "ntp", "vagrant"]`
     ✔  nobody should be listed in allowed users.
     ✔  dbus should be listed in allowed users.
     ×  systemd-coredump should be listed in allowed users.
     expected `systemd-coredump` to be in the list: `["root", "bin", "daemon", "adm", "lp", "sync", "shutdown", "halt", "mail", "operator", "nobody", "systemd-bus-proxy", "dbus", "polkitd", "postfix", "sssd", "chrony", "systemd-network", "sshd", "ntp", "vagrant"]`
     ×  systemd-resolve should be listed in allowed users.
     expected `systemd-resolve` to be in the list: `["root", "bin", "daemon", "adm", "lp", "sync", "shutdown", "halt", "mail", "operator", "nobody", "systemd-bus-proxy", "dbus", "polkitd", "postfix", "sssd", "chrony", "systemd-network", "sshd", "ntp", "vagrant"]`
     ×  tss should be listed in allowed users.
     expected `tss` to be in the list: `["root", "bin", "daemon", "adm", "lp", "sync", "shutdown", "halt", "mail", "operator", "nobody", "systemd-bus-proxy", "dbus", "polkitd", "postfix", "sssd", "chrony", "systemd-network", "sshd", "ntp", "vagrant"]`
     ✔  polkitd should be listed in allowed users.
     ×  unbound should be listed in allowed users.
     expected `unbound` to be in the list: `["root", "bin", "daemon", "adm", "lp", "sync", "shutdown", "halt", "mail", "operator", "nobody", "systemd-bus-proxy", "dbus", "polkitd", "postfix", "sssd", "chrony", "systemd-network", "sshd", "ntp", "vagrant"]`
     ✔  sssd should be listed in allowed users.
     ✔  chrony should be listed in allowed users.
     ✔  sshd should be listed in allowed users.
     ×  ec2-user should be listed in allowed users.
     expected `ec2-user` to be in the list: `["root", "bin", "daemon", "adm", "lp", "sync", "shutdown", "halt", "mail", "operator", "nobody", "systemd-bus-proxy", "dbus", "polkitd", "postfix", "sssd", "chrony", "systemd-network", "sshd", "ntp", "vagrant"]`
     ✔  postfix should be listed in allowed users.

Which accounts to add to inspect.yml, which accounts to add to remediation to remove users

**Comment by wdower** [comment]
We updated inspec.yml and the tests that use this input with a reasonable default. Users who need a different list can override the input.
