### ISSUE TITLE
/var/log/messages should have container tag removed or check if exists to skip invalid tests

### ISSUE THREAD

**Issue by bordencastle** [mitre/redhat-enterprise-linux-8-stig-baseline-old#47]
The following checks are not valid for container checks, or the logic should check if the /var/log/messages file exists and skip if it does not exist:

References:
https://repo1.dso.mil/dsop/redhat/ubi/8.x/ubi8/-/blob/development/Dockerfile?ref_type=heads#L86 --> indicates not valid for ubi8
https://github.com/RedHatOfficial/ansible-role-rhel8-stig/blob/9a306275522b4ce290cdb7ca7088a94d597d281f/tasks/main.yml#L39007 --> indicates only valid if file exists

SV | RHEL STIG ID | Description
-- | -- | --
SV-230245 | RHEL-08-010210 | File   /var/log/messages is expected to exist
SV-230246 | RHEL-08-010220 | File   /var/log/messages is expected to exist      File /var/log/messages is expected to be owned by "root"
SV-230247 | RHEL-08-010230 | File   /var/log/messages is expected to exist

The SELINUX checks SV-250315 seem a little strange as well for containers, as the container is probably going to show disabled unless the underlying OS has SELINUX enabled? See RedHat Official SELINUX skips based on virtualization. [- ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"] ](https://github.com/RedHatOfficial/ansible-role-rhel8-stig/blob/9a306275522b4ce290cdb7ca7088a94d597d281f/tasks/main.yml#L45169)

**Comment by wdower** [comment]
@bordenit Resolved this for a patch release for v1r12. Good catch.

We generally mark anything related to the kernel (audit, selinux etc) as not applicable for containers for similar reasons to the ones you mention here -- these were oversights.
